# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Promissory-UI-SC'
    organization: 'aumnitec'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Aumnitec_Promissory'
    cliProjectName: 'Promissory'
    cliSources: '.'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'